.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. GameBit_qt test_GameBit_qt
clean: FORCE
	$(MAKE) -C .. GameBit_qt_clean test_GameBit_qt_clean
check: FORCE
	$(MAKE) -C .. test_GameBit_qt_check
GameBit-qt GameBit-qt.exe: FORCE
	 $(MAKE) -C .. GameBit_qt
